<Project>
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <Version>0.6.0</Version>
    <Product>Testy Windows test studio</Product>
  </PropertyGroup>
</Project>
